[2023-09-04T13:25:15.957+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-09-04T13:25:15.980+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-09-04T13:25:15.980+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 6
[2023-09-04T13:25:16.029+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-01-29 00:00:00+00:00
[2023-09-04T13:25:16.040+0000] {standard_task_runner.py:57} INFO - Started process 5851 to run task
[2023-09-04T13:25:16.058+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_with_python_dependencies_v03', 'get_sklearn', 'scheduled__2023-01-29T00:00:00+00:00', '--job-id', '3512', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_python_dependencies.py', '--cfg-path', '/tmp/tmpmnds1pj5']
[2023-09-04T13:25:16.067+0000] {standard_task_runner.py:85} INFO - Job 3512: Subtask get_sklearn
[2023-09-04T13:25:16.241+0000] {task_command.py:415} INFO - Running <TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-29T00:00:00+00:00 [running]> on host 55ba52c92856
[2023-09-04T13:25:16.469+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dags_with_python_dependencies_v03' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-01-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-29T00:00:00+00:00'
[2023-09-04T13:25:16.473+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_with_python_dependencies.py", line 16, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-09-04T13:25:16.490+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dags_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20230129T000000, start_date=20230904T132515, end_date=20230904T132516
[2023-09-04T13:25:16.527+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3512 for task get_sklearn (No module named 'sklearn'; 5851)
[2023-09-04T13:25:16.558+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T13:25:16.600+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
