[2023-09-04T13:50:51.632+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-02-06T00:00:00+00:00 [queued]>
[2023-09-04T13:50:51.652+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-02-06T00:00:00+00:00 [queued]>
[2023-09-04T13:50:51.653+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2023-09-04T13:50:51.683+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-02-06 00:00:00+00:00
[2023-09-04T13:50:51.696+0000] {standard_task_runner.py:57} INFO - Started process 6442 to run task
[2023-09-04T13:50:51.704+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_with_python_dependencies_v03', 'get_sklearn', 'scheduled__2023-02-06T00:00:00+00:00', '--job-id', '3553', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_python_dependencies.py', '--cfg-path', '/tmp/tmpf06di0cb']
[2023-09-04T13:50:51.709+0000] {standard_task_runner.py:85} INFO - Job 3553: Subtask get_sklearn
[2023-09-04T13:50:51.810+0000] {task_command.py:415} INFO - Running <TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-02-06T00:00:00+00:00 [running]> on host 55ba52c92856
[2023-09-04T13:50:52.146+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dags_with_python_dependencies_v03' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-02-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-06T00:00:00+00:00'
[2023-09-04T13:50:52.152+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_with_python_dependencies.py", line 16, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-09-04T13:50:52.177+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dags_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20230206T000000, start_date=20230904T135051, end_date=20230904T135052
[2023-09-04T13:50:52.204+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3553 for task get_sklearn (No module named 'sklearn'; 6442)
[2023-09-04T13:50:52.251+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T13:50:52.309+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
