[2023-09-04T13:55:55.532+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-02-08T00:00:00+00:00 [queued]>
[2023-09-04T13:55:55.576+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-02-08T00:00:00+00:00 [queued]>
[2023-09-04T13:55:55.576+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 6
[2023-09-04T13:55:55.668+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-02-08 00:00:00+00:00
[2023-09-04T13:55:55.714+0000] {standard_task_runner.py:57} INFO - Started process 6901 to run task
[2023-09-04T13:55:55.739+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_with_python_dependencies_v03', 'get_sklearn', 'scheduled__2023-02-08T00:00:00+00:00', '--job-id', '3573', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_python_dependencies.py', '--cfg-path', '/tmp/tmpp5mmj4qx']
[2023-09-04T13:55:55.767+0000] {standard_task_runner.py:85} INFO - Job 3573: Subtask get_sklearn
[2023-09-04T13:55:56.256+0000] {task_command.py:415} INFO - Running <TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-02-08T00:00:00+00:00 [running]> on host 55ba52c92856
[2023-09-04T13:55:56.732+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dags_with_python_dependencies_v03' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-02-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-08T00:00:00+00:00'
[2023-09-04T13:55:56.743+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_with_python_dependencies.py", line 16, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-09-04T13:55:56.783+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dags_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20230208T000000, start_date=20230904T135555, end_date=20230904T135556
[2023-09-04T13:55:56.835+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3573 for task get_sklearn (No module named 'sklearn'; 6901)
[2023-09-04T13:55:56.875+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T13:55:56.954+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
