[2023-09-04T12:32:47.349+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2023-09-04T12:32:47.363+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2023-09-04T12:32:47.364+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T12:32:47.450+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-01-08 00:00:00+00:00
[2023-09-04T12:32:47.458+0000] {standard_task_runner.py:57} INFO - Started process 1338 to run task
[2023-09-04T12:32:47.461+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_with_python_dependencies_v03', 'get_sklearn', 'scheduled__2023-01-08T00:00:00+00:00', '--job-id', '3330', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_python_dependencies.py', '--cfg-path', '/tmp/tmpi4hs5rjy']
[2023-09-04T12:32:47.464+0000] {standard_task_runner.py:85} INFO - Job 3330: Subtask get_sklearn
[2023-09-04T12:32:47.527+0000] {task_command.py:415} INFO - Running <TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-08T00:00:00+00:00 [running]> on host 55ba52c92856
[2023-09-04T12:32:47.638+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dags_with_python_dependencies_v03' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-08T00:00:00+00:00'
[2023-09-04T12:32:47.642+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_with_python_dependencies.py", line 16, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-09-04T12:32:47.652+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dags_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20230108T000000, start_date=20230904T123247, end_date=20230904T123247
[2023-09-04T12:32:47.670+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3330 for task get_sklearn (No module named 'sklearn'; 1338)
[2023-09-04T12:32:47.714+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T12:32:47.751+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-04T12:39:42.787+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2023-09-04T12:39:42.803+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2023-09-04T12:39:42.804+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T12:39:42.938+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-01-08 00:00:00+00:00
[2023-09-04T12:39:42.948+0000] {standard_task_runner.py:57} INFO - Started process 1943 to run task
[2023-09-04T12:39:42.952+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_with_python_dependencies_v03', 'get_sklearn', 'scheduled__2023-01-08T00:00:00+00:00', '--job-id', '3347', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_python_dependencies.py', '--cfg-path', '/tmp/tmp0trsz8z6']
[2023-09-04T12:39:42.956+0000] {standard_task_runner.py:85} INFO - Job 3347: Subtask get_sklearn
[2023-09-04T12:39:43.027+0000] {task_command.py:415} INFO - Running <TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-08T00:00:00+00:00 [running]> on host 55ba52c92856
[2023-09-04T12:39:43.139+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dags_with_python_dependencies_v03' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-08T00:00:00+00:00'
[2023-09-04T12:39:43.142+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_with_python_dependencies.py", line 16, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-09-04T12:39:43.154+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dags_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20230108T000000, start_date=20230904T123942, end_date=20230904T123943
[2023-09-04T12:39:43.173+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3347 for task get_sklearn (No module named 'sklearn'; 1943)
[2023-09-04T12:39:43.205+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T12:39:43.244+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
