[2023-09-04T05:33:29.986+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2023-09-04T05:33:30.031+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2023-09-04T05:33:30.035+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T05:33:30.159+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-01-01 00:00:00+00:00
[2023-09-04T05:33:30.172+0000] {standard_task_runner.py:57} INFO - Started process 2358 to run task
[2023-09-04T05:33:30.260+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'create_postgres_table', 'scheduled__2022-01-01T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp4qfs94e_']
[2023-09-04T05:33:30.290+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask create_postgres_table
[2023-09-04T05:33:30.811+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table scheduled__2022-01-01T00:00:00+00:00 [running]> on host 10bdc2e98230
[2023-09-04T05:33:31.340+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2022-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-01-01T00:00:00+00:00'
[2023-09-04T05:33:31.349+0000] {sql.py:274} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-09-04T05:33:31.430+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2023-09-04T05:33:31.442+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v03, task_id=create_postgres_table, execution_date=20220101T000000, start_date=20230904T053329, end_date=20230904T053331
[2023-09-04T05:33:31.480+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task create_postgres_table (The conn_id `postgres_localhost` isn't defined; 2358)
[2023-09-04T05:33:31.525+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T05:33:31.561+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
