[2023-09-04T05:45:20.021+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table scheduled__2021-12-24T00:00:00+00:00 [queued]>
[2023-09-04T05:45:20.067+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table scheduled__2021-12-24T00:00:00+00:00 [queued]>
[2023-09-04T05:45:20.070+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 6
[2023-09-04T05:45:20.135+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2021-12-24 00:00:00+00:00
[2023-09-04T05:45:20.164+0000] {standard_task_runner.py:57} INFO - Started process 3361 to run task
[2023-09-04T05:45:20.184+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'create_postgres_table', 'scheduled__2021-12-24T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmphqwcbn39']
[2023-09-04T05:45:20.193+0000] {standard_task_runner.py:85} INFO - Job 79: Subtask create_postgres_table
[2023-09-04T05:45:20.608+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table scheduled__2021-12-24T00:00:00+00:00 [running]> on host 10bdc2e98230
[2023-09-04T05:45:21.025+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2021-12-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-12-24T00:00:00+00:00'
[2023-09-04T05:45:21.029+0000] {sql.py:274} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-09-04T05:45:21.092+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2023-09-04T05:45:21.106+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v03, task_id=create_postgres_table, execution_date=20211224T000000, start_date=20230904T054520, end_date=20230904T054521
[2023-09-04T05:45:21.145+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 79 for task create_postgres_table (The conn_id `postgres_localhost` isn't defined; 3361)
[2023-09-04T05:45:21.192+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T05:45:21.320+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
