[2023-09-04T12:32:48.965+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-15T00:00:00+00:00 [queued]>
[2023-09-04T12:32:48.977+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-15T00:00:00+00:00 [queued]>
[2023-09-04T12:32:48.978+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T12:32:48.998+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-01-15 00:00:00+00:00
[2023-09-04T12:32:49.005+0000] {standard_task_runner.py:57} INFO - Started process 1349 to run task
[2023-09-04T12:32:49.008+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_with_python_dependencies_v03', 'get_sklearn', 'scheduled__2023-01-15T00:00:00+00:00', '--job-id', '3337', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_python_dependencies.py', '--cfg-path', '/tmp/tmp9kf1johr']
[2023-09-04T12:32:49.011+0000] {standard_task_runner.py:85} INFO - Job 3337: Subtask get_sklearn
[2023-09-04T12:32:49.068+0000] {task_command.py:415} INFO - Running <TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-15T00:00:00+00:00 [running]> on host 55ba52c92856
[2023-09-04T12:32:49.172+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dags_with_python_dependencies_v03' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-01-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-15T00:00:00+00:00'
[2023-09-04T12:32:49.175+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_with_python_dependencies.py", line 16, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-09-04T12:32:49.185+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dags_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20230115T000000, start_date=20230904T123248, end_date=20230904T123249
[2023-09-04T12:32:49.201+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3337 for task get_sklearn (No module named 'sklearn'; 1349)
[2023-09-04T12:32:49.222+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T12:32:49.253+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-04T12:39:44.395+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-15T00:00:00+00:00 [queued]>
[2023-09-04T12:39:44.405+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-15T00:00:00+00:00 [queued]>
[2023-09-04T12:39:44.405+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T12:39:44.419+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-01-15 00:00:00+00:00
[2023-09-04T12:39:44.426+0000] {standard_task_runner.py:57} INFO - Started process 1953 to run task
[2023-09-04T12:39:44.428+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_with_python_dependencies_v03', 'get_sklearn', 'scheduled__2023-01-15T00:00:00+00:00', '--job-id', '3354', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_python_dependencies.py', '--cfg-path', '/tmp/tmpth2tb3qd']
[2023-09-04T12:39:44.431+0000] {standard_task_runner.py:85} INFO - Job 3354: Subtask get_sklearn
[2023-09-04T12:39:44.479+0000] {task_command.py:415} INFO - Running <TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-01-15T00:00:00+00:00 [running]> on host 55ba52c92856
[2023-09-04T12:39:44.558+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dags_with_python_dependencies_v03' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-01-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-15T00:00:00+00:00'
[2023-09-04T12:39:44.560+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_with_python_dependencies.py", line 16, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-09-04T12:39:44.568+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dags_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20230115T000000, start_date=20230904T123944, end_date=20230904T123944
[2023-09-04T12:39:44.581+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3354 for task get_sklearn (No module named 'sklearn'; 1953)
[2023-09-04T12:39:44.601+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T12:39:44.625+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
