[2023-09-04T13:45:50.550+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-02-11T00:00:00+00:00 [queued]>
[2023-09-04T13:45:50.558+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-02-11T00:00:00+00:00 [queued]>
[2023-09-04T13:45:50.559+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-04T13:45:50.572+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-02-11 00:00:00+00:00
[2023-09-04T13:45:50.578+0000] {standard_task_runner.py:57} INFO - Started process 5996 to run task
[2023-09-04T13:45:50.581+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_with_python_dependencies_v03', 'get_sklearn', 'scheduled__2023-02-11T00:00:00+00:00', '--job-id', '3541', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_python_dependencies.py', '--cfg-path', '/tmp/tmpuwpm9t3y']
[2023-09-04T13:45:50.583+0000] {standard_task_runner.py:85} INFO - Job 3541: Subtask get_sklearn
[2023-09-04T13:45:50.623+0000] {task_command.py:415} INFO - Running <TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-02-11T00:00:00+00:00 [running]> on host 55ba52c92856
[2023-09-04T13:45:50.696+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dags_with_python_dependencies_v03' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-11T00:00:00+00:00'
[2023-09-04T13:45:50.698+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_with_python_dependencies.py", line 16, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-09-04T13:45:50.705+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dags_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20230211T000000, start_date=20230904T134550, end_date=20230904T134550
[2023-09-04T13:45:50.717+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3541 for task get_sklearn (No module named 'sklearn'; 5996)
[2023-09-04T13:45:50.753+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T13:45:50.814+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
